[misc]
devMode = false
autoSwitchLanguage = true
checkModPackTranslationUpdate = true
[resourcePack]
autoDownloadVMTranslationPack = false
autoLoadExtraTranslationPack = true
resourcePackIndex = "TOP_OF_CFPA"
extraPackName = "VM Language Override"
extraPackCustomIndex = 0
[modInstallCheck]
i18nUpdateMod = true
vaultPatcher = false
textureLocaleRedirector = false
